# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-01-02 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_recurringtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='transactionsStr',
            field=models.TextField(default=b'[]'),
        ),
    ]
