# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-03-02 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_recurringtransaction_transactionsstr'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
