# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-03-02 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_location_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='inactive_years',
            field=models.ManyToManyField(to='budget.Year'),
        ),
    ]
