# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-03-05 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_subcategory_inactive_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('I', 'Income'), ('E', 'Expense'), ('V', 'Investment')], max_length=1),
        ),
    ]
