# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-03-05 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20160305_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='inactive_years',
            field=models.ManyToManyField(blank=True, to='budget.Year'),
        ),
    ]
