# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-03-05 08:44
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20160305_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybalances',
            name='budgeted_investments',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=7),
        ),
        migrations.AddField(
            model_name='monthlybalances',
            name='total_investments',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=7),
        ),
    ]
