# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20160305_0344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringtransaction',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('I', 'Income'), ('M', 'Mandatory'), ('E', 'Expense'), ('V', 'Investment')], max_length=1),
        ),
    ]
