# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 13:49
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20160711_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybalances',
            name='budgeted_mandatory',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=7),
        ),
        migrations.AddField(
            model_name='monthlybalances',
            name='total_mandatory',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=7),
        ),
    ]
